name: Build and Deploy to S3

on: 
  push:
    branches:
      - "main"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # replace this with your aws-region
      - run: npm ci
      - run: node ./scripts/compileData.mjs
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
      - run: ls _data
      - run: ls scripts
      - run: ls
      - name: Build the website
        run: npx @11ty/eleventy
      - name: Upload files to S3 with AWS CLI
        run: |
          aws s3 sync _site/ s3://${{ secrets.S3_BUCKET }} --acl public-read